name: Audit ZAP

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL à auditer'
        required: true
        default: 'https://www.softibox.com'

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Lancer OWASP ZAP contre le site
      uses: zaproxy/action-full-scan@v0.7.0
      with:
        target: ${{ github.event.inputs.target_url }}
        cmd_options: '-a'
        fail_action: false

    - name: Télécharger le rapport
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: report_html.html
